version: "3.0"
services:
  lotto_analytics:
    image: lotto_analytics
    depends_on:
      - kibana
    networks:
      - lotto_network
  elasticsearch:
    image: elasticsearch:7.3.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - lotto_network
  kibana:
    image: kibana:7.3.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - lotto_network

networks:
  lotto_network:
