version: "3.5"

services:
  python:
    image: lotto_analytics:${TARGET}
    container_name: lotto_analytics_python
    build: 
      context: './docker/python/'
      target: ${TARGET}
    depends_on:
      - kibana
    networks:
      - backend
    volumes:
      - ./app/:/app
  elasticsearch:
    container_name: lotto_analytics_elasticsearch
    image: elasticsearch:7.3.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - backend
      - frontend
  kibana:
    container_name: lotto_analytics_kibana
    image: kibana:7.3.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - frontend

networks:
  backend:
    name: lotto_analytics_back
  frontend:
    name: lotto_analytics
